services:
  librechat:
    build:
      context: .
    depends_on:
      - mongodb
    environment:
      CREDS_IV: e2341419ec3dd3d19b13a1a87fafcbfb
      CREDS_KEY: f34be427ebb29de8d88c107a71546019685ed8b241d8f2ed00c3df97ad2566f0
      JWT_REFRESH_SECRET: eaa5191f2914e30b9387fd84e254e4ba6fc51b4654968a9b0803b456a54b8418
      JWT_SECRET: 16f8c0ef4a5d391b26034086c628469d3f9f497f08163ab9b40137092f2909ef
      MONGO_URI: mongodb://mongodb:27017/LibreChat
      ALLOW_REGISTRATION: true
    ports:
      - 3080:3080
    restart: always
  mongodb:
    command: mongod --noauth
    image: mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data: null
